### PR TITLE
fix data preview on search/data preview/data query

### LINKED ISSUE #223: No Data in Data Preview after upgrade from 2.2.5 to 2.2.6 or 2.2.7
**Describe the bug:**
No Data in Data Preview, but ```Approx Entity Count``` show the correct number.
After downgrade back to 2.2.5, data appeared again.

Also while open app show the following error info if the connection was not closed last time.
```TypeError: Cannot read properties of undefined (reading 'showCollections')```
Then click close connection
```TypeError: Cannot read properties of undefined (reading 'closeConnection')```

**Steps to reproduce:**
1. Upgrade from 2.2.5 to 2.2.7
2. Open app
3. Open the Data Preview page of the old collection
4. Close Connection

**Attu version:**
2.2.6,2.2.7

**Attu version:**

### PR DESCRIPTION
**Pull request by shanghaikid**
image
image
image

this fix #223

### CODE REVIEW

File: client/src/hooks/Result.tsx [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    () =>
+      searchResult?.map((resultItem: { [key: string]: any }) => {
+        // Iterate resultItem keys, then format vector(array) items.
+
+        const tmp = Object.keys(resultItem).reduce(
+          (prev: { [key: string]: any }, item: string) => {
+            const itemType = detectItemType(resultItem[item]);
+
+            switch (itemType) {
+              case 'json':
```
Comment (nameczz) [inline client/src/hooks/Result.tsx:21]: Should we use enum for these types?

**Review by nameczz — APPROVED** [review]

File: client/src/hooks/Result.tsx (hunk 1 above)
Comment (shanghaikid) [reply client/src/hooks/Result.tsx:21]: I don't think so, string is enough here.
