### PR TITLE
fix varchar deleting issue

### LINKED ISSUE #185: milvus collection 主键是 varchar 时，attu删除entities时，会报错
**Describe the bug:**

**Steps to reproduce:**
1.
2.
3.

**Attu version:**

**Attu version:**

### PR DESCRIPTION
**Pull request by shanghaikid**
this fix #185

### CODE REVIEW

File: client/src/pages/query/Query.tsx [hunk 1]
```diff
@@ -104,9 +106,10 @@ const Query: FC<{
       name: v.name,
       type: v.data_type,
     }));
-    const primaryKey =
-      schemaList.find(v => v._isPrimaryKey === true)?._fieldName || '';
-    setPrimaryKey(primaryKey);
+    const primaryKey = schemaList.find(v => v._isPrimaryKey === true)!;
+    setPrimaryKey({ value: primaryKey['name'], type: primaryKey['data_type'] });
+
+    console.log(schemaList.find(v => v._isPrimaryKey === true));
```
Comment (nameczz) [inline client/src/pages/query/Query.tsx:112]: remove connsole

**Review by nameczz — CHANGES_REQUESTED** [review]

**Review by nameczz — APPROVED** [review]
